### ISSUE TITLE
The .npmrc file did not get created in the new React project, when the customized template was used

### ISSUE THREAD

**Issue by aksconnect42** [ihaback/create-react-app-template#1]
Hello, Thanks for creating this create-react-app-template. It is exceedingly helpful. 

I've been able to copy over all files and folders that I needed in my template, except the .npmrc file.  
I am not sure why the .npmrc file was ignored / skipped when the new project was generated based on the template. I made sure to copy the .npmrc file in the template folder before publishing the template, but yet it was not a part of the project that was based on the template. 

Not having the .npmrc file in the React project is preventing some dependencies to be installed in the developer's machine if they do not have global npm configurations set on their machine. 

I am looking for a solution for this. Thanks !

**Comment by ihaback** [comment]
Hello @aksconnect42 

I performed the following steps:

1. Cloned the repo.
2. Created .npmrc  in the `template` folder  with some content in it,´,
3. Ran `npx create-react-app my-app --template file:. ` in the root. This generated an `my-app` folder with a `.npmrc` in it.

If you have published your own version of to npm without the `.npmrc` before, you might need to run `npm version minor` and `npm publish` it again.

**Comment by aksconnect42** [comment]
Thanks for your response @ihaback I didn't understand this step :

Ran `npx create-react-app my-app --template file:.`  in the root.  
I have been running `npx create-react-app my-app --template` and expecting that the .npmrc file in the template folder will be copied over as is because that is how it has been working for all other files and folders. 

Do we need to run `npx create-react-app my-app --template file:.` separately for the .npmrc file to get copied over ?

**Comment by ihaback** [comment]
I get the same result when scaffolding from the npm package. Not sure if you can include .npmrc like this when publishing to npmjs. Other files seem to be fine, but not `.npmrc`
https://docs.npmjs.com/cli/v8/configuring-npm/npmrc#per-project-config-file
